language: r

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: COVERALLS_TEST=true
    - os: linux
      r: devel
    - os: osx
      r: release
      disable_homebrew: true

sudo: false
cache: packages
warnings_are_errors: true

r_github_packages:
    - hadley/testthat
    - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [ "${COVERALLS_TEST}" ]; then Rscript -e 'covr::coveralls()'; fi